window.language = window.language || {};
window.language['cn'] = {
    'total': '总金额',
    'locked': '锁定余额',
    'available': '可用余额',
    'send': '转账',
    'sending': '转账中...',
    'submit': '提交',
    'center_password': '密码',
    'profile': '个人资料',
    'center_logout': '退出',
    'change_btn': '修改',
    'wallet_password': '钱包密码',

    'menu_home': '首页',
    'menu_send': '转账',
    'menu_transactions': '交易记录',

    'yourwallet': '钱包地址',
    'transactions': '交易',
    'recent_transactions': '最近交易',
    'block': '区块',
    'date': '时间',
    'hash': '哈希',
    'amount': '数量',
    'pending': '待确认',

    'pay_to': '转账目标地址',
    'amount': '数量',
    'fee': '手续费',
    'anonymity_level': '匿名级别',
    'payment_id': '支付ID <small>(可选)</small>',

    'unknown_error': '未知错误',
    'tip_amount': '请输入转账数量',
    'tip_fee': '请输入手续费',
    'tip_copy_clipboard': '复制到剪切板',
    'tip_copied': '已复制',
    'tip_wallet_password': '请输入钱包密码',
    'tip_send_success': '转账成功',
    'tip_change_password': '请输入新密码',
    'tip_email_password': '请填写您的邮箱和密码',
    'tip_email_err': '邮箱格式错误',
    'tip_enter_email': '请输入邮箱地址',
    'tip_enter_password': '请输入密码',
    'tip_you_signed': '您已成功注册，请登录',
    'tip_agree': '同意<a href="/tos.html" target="_blank">使用条款和条件</a>',
    'tip_length_6': '密码长度必须大于6位',
    'tip_passwords_confirm': '两次输入的密码必须相同',
    'tip_must_agree': '您必须同意使用条款和条件',

    'reg_title': '注册 BBS.money 账号',
    'login_title': '登录 BBS.money',
    'email_address': '邮箱地址',
    'signing': '登录中...',
    'registering': '注册中...',
    'sign_in': '登录',
    'here_sign': ' 立即登录',
    'here_reg': ' 立即注册',
    'not_account': '没有账号?',
    'has_account': '已经有帐号?',
    'password': '密码',
    'confirm_password': '确认密码',
    'register': '注册',
    'tip_repeat_wallet_password': '再次输入钱包密码',
    'tip_mixing': '无效的匿名级别',
    'tip_backup_copied': '备份信息已复制',
    'tip_wallet_password_warning': '请为你的新钱包设置一个密码。密码长度必须大于6位。<br>BBS.money 只会在服务器上保存加密后的密钥。<br>我们将在下一步显示你的密钥。<br>如果你丢失了他们，我们将无法恢复你的钱包。<br>',
    'tip_backup_warning': '<b>下面是你钱包的密钥，请确保备份好这些信息。</b><br><br><b>千万不要丢失！</b> 如果你丢了这些，你将无法找回钱包。<br><b>不要分享给别人！</b> 如果你把这些信息不慎泄漏，你的财产可能会被盗。<br><b>做好备份！</b> 像对待数百万钞票一样对待这些信息。<br>',
    'tip_backup_info': '请备份下列信息',
    'new_wallet_title': '创建新钱包',
    'backup_keys_title': '备份密钥',
    'backup_understand': '我已经备份好我的钱包地址和密钥',
    'confirmed': '已确认',
    'cancelled': '已取消',
    'no_transaction': '没有交易记录',
    'transaction_details': '交易详情',
    'tx_details_hash': '哈希',
    'tx_details_status': '状态',
    'tx_details_block_number': '区块高度',
    'tx_details_time': '时间',
    'tx_details_confirmations': '确认数',
    'tx_details_unlock_time': '解锁时机',
    'tx_details_amount': '金额',
    'tx_details_transaction_fee': '手续费',
    'tx_details_payment_id': '支付ID',
    'destination_address': '目标地址',
    'unlock_wallet': '解锁钱包',
    'unlock_processing': '正在同步数据<br>请稍等片刻',
    'server_status': '服务器状态',
    'last_synced': '最后同步区块',
    'last_updated': '最后同步时间',
    'maintenance': '维护',
    'walletAddress': '钱包地址',
    'viewSecret': 'View Secret 备份短语',
    'spendSecret': 'Spend Secret 备份短语',
    'newWalletPassword': '新钱包密码',
    'tip_wallet_password_changed_success': '钱包密码修改成功',
    'tip_view_phase': '创建钱包时给出的24个单词 View Secret 备份信息',
    'tip_spend_phase': '创建钱包时给出的24个单词 Spend Secret 备份信息',
    'reset_wallet_password': '重置钱包密码',
    'create_new_address': '创建新钱包地址',
    'login_html_title': '登录 | BBS.money',
    'register_html_title': '注册 | BBS.money',
    'reset_html_title': '重置密码 | BBS.money',
    'modify_account_password': '修改账户密码',
    'old_password': '旧密码',
    'new_password': '新密码',
    'confirm_new_password': '确认新密码',
    'tip_account_password_changed_success': '账户密码修改成功',
    'tip_old_new_password': '请输入旧密码和新密码',
    'tip_email': '请输入邮箱地址',
    'reset_account_password': '重置账户密码',
    'send_reset_mail': '发送重置邮件',
    'forget_password': '忘记密码了？',
    'reset_password': '重置密码',
    'verify_account': '账户认证',
    'verify_account_html_title': '账户认证 | BBS.money',
    'verification_code': '认证码',
    'tip_incorrect_verification_code': '无效的认证码',
    'tip_verification': '认证码不能为空',
    'verifying': '正在认证...',
    'tip_account_verified': '账户已成功认证，请登录。',
    'tip_needs_verification': '感谢你注册 BBS.money <br>为了完成注册，请检查你的电子邮箱并根据指引激活账户。 <br>请注意，激活认证码有效期为24小时内。',
    'tip_reset_email_sent': '感谢你的支持，我们已经发送了一封邮件到你的邮箱中，用来指导你如何重置密码。',
    'tip_new_password_email_sent': '感谢你的支持，密码已经重置并发送到你的邮箱中。',
    'tip_wrong_verification_for_new_password': '账户错误或者认证码错误',
    'tos_html_title': '使用条款 | BBS.money',
    'tip_pay_to': '请输入转账目标地址',
    'invalid_amount': '无效金额',
    'amount_too_big': '金额过大',
    'tip_new_address': '每个账户最多有2个钱包地址',
    'api_access': 'API 权限',
    'generate_app_key': '生成 App Key',
    'revoke_app_key': '注销 App Key',
    'tip_api_access': 'App Id 和 App Key 允许你将第三方服务与 BBS.money 集成',
    'tip_existing_api_access': '为当前钱包地址服务的 App Id 已经生成 <br>为了安全，我们不会显示 App Key <br>如果你丢失了 App Key，你应该重新生成一个。 ',
    'tip_new_api_access': '请在安全的地方保存好你的 App Key。我们以后将不会再显示这个Key。',
    'app_id': 'App Id',
    'tip_app_id': 'App Id 用来标识钱包地址',
    'app_key': 'App Key',
    'tip_app_key': 'App Key 需要被严密保存。请像钱包密码一样对待Key。',
    'generate_import_key': '生成 Import Key',
    'recover_from_backup': '从备份恢复?',
    'tip_generate_import_key': '你可以生成 Import key 用来将钱包导入到桌面钱包软件中。<br>请点击桌面钱包的 File 菜单 > Import key 来导入。',
    'import_key_for_this_address': '当前钱包的 Import key',
    'tip_import_key_for_this_address': '请确保 Import key 存放于安全的地方。不要分享给任何人。',
};