window.language = window.language || {};
window.language['en'] = {
    'total': 'Total',
    'locked': 'Locked',
    'available': 'Available',
    'send': 'SEND',
    'sending': 'SENDING...',
    'submit': 'Submit',
    'center_password': 'password',
    'profile': 'Profile',
    'center_logout': 'Logout',
    'change_btn': 'change',
    'wallet_password': 'Wallet Password',

    'menu_home': 'Overview',
    'menu_send': 'Send',
    'menu_transactions': 'Transactions',

    'yourwallet': 'Your wallet',
    'transactions': 'Transactions',
    'recent_transactions': 'Recent transactions',
    'block': 'Block',
    'date': 'Date',
    'hash': 'Hash',
    'amount': 'Amount',
    'pending': 'Pending',

    'pay_to': 'Destination address',
    'amount': 'Amount',
    'fee': 'Fee',
    'anonymity_level': 'Anonymity level',
    'payment_id': 'Payment id  <small>(optional)</small>',

    'unknown_error': 'Unknown error',
    'tip_amount': 'Please enter amount',
    'tip_fee': 'Please enter transaction fee',
    'tip_copy_clipboard': 'Copy to clipboard',
    'tip_copied': 'Address has been copied',
    'tip_wallet_password': 'Enter wallet password',
    'tip_send_success': 'Transaction has been submitted, transcation hash is: <br>',
    'tip_change_password': 'Change password',
    'tip_email_password': 'Please input your email and password',
    'tip_email_err': 'Email format validation error',
    'tip_enter_email': 'Email',
    'tip_enter_password': 'Password',
    'tip_you_signed': 'You have successfully registered, please sign in.',
    'tip_agree': 'Agree the <a href="/tos.html" target="_blank">Terms of Service and Use</a>',
    'tip_length_6': 'The length of password must be greater than 6',
    'tip_passwords_confirm': 'The passwords are not matching',
    'tip_must_agree': 'You must agree with the Terms of Service and Use',

    'reg_title': 'Register a BBS.money account',
    'login_title': 'Welcome to BBS.money',
    'email_address': 'Email Address',
    'signing': 'Signing...',
    'registering': 'Registering...',
    'sign_in': 'Sign In',
    'here_sign': ' Sign In',
    'here_reg': ' Sign up here',
    'not_account': 'Don\'t have an account?',
    'has_account': 'Already have an account?',
    'password': 'Password',
    'confirm_password': 'Confirm Password',
    'register': 'Register',
    'tip_repeat_wallet_password': 'Repeat Wallet Password',
    'tip_mixing': 'Wrong anonymity level',
    'tip_backup_copied': 'Backup information has been copied',
    'tip_wallet_password_warning': 'Please choose a password for your new wallet. It must be greater than 6 characters.<br>BBS.money only stores encrypted keys on the server. <br>Your private keys will be shown on the next screen. <br>Please note, we cannot recover your wallet if you lose them.',
    'tip_backup_warning': '<b>Following keys are your secret keys for this wallet. Please make sure you backup them.</b><br><br><b>Do not lose it!</b> It cannot be recovered if you lose it.<br><b>Do not share it!</b> Your funds will be stolen if you use this file on a malicious/phishing site.<br><b>Make a backup!</b> Secure it like the millions of dollars it may one day be worth.<br>',
    'tip_backup_info': 'Please backup following information',
    'new_wallet_title': 'Create a new wallet',
    'backup_keys_title': 'Backup keys',
    'backup_understand': 'I have backed up my address and secret keys',
    'confirmed': 'Confirmed',
    'cancelled': 'Cancelled',
    'no_transaction': 'No transaction records',
    'transaction_details': 'Transaction Details',
    'tx_details_hash': 'Hash',
    'tx_details_status': 'Status',
    'tx_details_block_number': 'Block Number',
    'tx_details_time': 'Time',
    'tx_details_confirmations': 'Confirmations',
    'tx_details_unlock_time': 'Unlock Time',
    'tx_details_amount': 'Amount',
    'tx_details_transaction_fee': 'Transaction Fee',
    'tx_details_payment_id': 'Payment ID',
    'destination_address': 'Destination Address',
    'unlock_wallet': 'Unlock Wallet',
    'unlock_processing': 'Processing transactions<br>Please wait for a while',
    'server_status': 'Server status',
    'last_synced': 'Last synced',
    'last_updated': 'Last updated',
    'maintenance': 'Maintenance',
    'walletAddress': 'Wallet Address',
    'viewSecret': 'View secret backup phrases',
    'spendSecret': 'Spend secret backup phrases',
    'newWalletPassword': 'New wallet password',
    'tip_wallet_password_changed_success': 'Wallet password has been changed successfully',
    'tip_view_phase': 'The 24-word phrase for view secret key when you created the wallet',
    'tip_spend_phase': 'The 24-word phrase for spend secret key when you created the wallet',
    'reset_wallet_password': 'Reset wallet password',
    'create_new_address': 'Create a new address',
    'login_html_title': 'Login | BBS.money',
    'register_html_title': 'Register | BBS.money',
    'reset_html_title': 'Reset Password | BBS.money',
    'modify_account_password': 'Modify Account Password',
    'old_password': 'Old Password',
    'new_password': 'New Password',
    'confirm_new_password': 'Confirm New Password',
    'tip_account_password_changed_success': 'Account password has been changed successfully',
    'tip_old_new_password': 'Please input your old password and new password',
    'tip_email': 'Please input your email',
    'reset_account_password': 'Reset Account Password',
    'send_reset_mail': 'Send reset mail',
    'forget_password': 'Forgot your password?',
    'reset_password': 'Reset Password',
    'verify_account': 'Verify Account',
    'verify_account_html_title': 'Verify Account | BBS.money',
    'verification_code': 'Verification Code',
    'tip_incorrect_verification_code': 'Incorrect verification code',
    'tip_verification': 'Verification code cannot be empty',
    'verifying': 'Verifying...',
    'tip_account_verified': 'Account has been verified, please sign in.',
    'tip_needs_verification': 'Thank you for registering on BBS.money. <br>To complete your registration, please check your email for account activation instructions. <br>Please note the verification code expires in 24 hours.',
    'tip_reset_email_sent': 'Thank you, an email with details on how to reset the password has been sent to the matching account.',
    'tip_new_password_email_sent': 'Thank you, an email with the new temporary password has been sent.',
    'tip_wrong_verification_for_new_password': 'Cannot find the account or invalid verification code.',
    'tos_html_title': 'Terms of Service and Use | BBS.money',
    'tip_pay_to': 'Please enter destination address',
    'invalid_amount': 'Invalid amount',
    'amount_too_big': 'Amount too big',
    'tip_new_address': 'Each account can create maximum 2 wallet addresses at the moment.',
    'api_access': 'API access',
    'generate_app_key': 'Generate a new App Key',
    'revoke_app_key': 'Revoke the App Key',
    'tip_api_access': 'App Id and App Key allows you to integrate BBS.money with third parties or services.',
    'tip_existing_api_access': 'Following App Id has been generated for this address. <br>For your protection, we do not show the App Key. <br>If you misplace your App Key, you should generate a new one. ',
    'tip_new_api_access': 'Please keep your app key in a safe place. We will not show it again.',
    'app_id': 'App Id',
    'tip_app_id': 'App Id is used for identify this wallet address',
    'app_key': 'App Key',
    'tip_app_key': 'App Key should be stored in a safe place. Please treat it as your wallet secret.',
    'generate_import_key': 'Generate the import key',
    'recover_from_backup': 'Recover from backup?',
    'tip_generate_import_key': 'You can generate the import key for importing your web wallet to the desktop wallet.<br>Please click "File" > "Import key" on the desktop wallet then paste in the import key.',
    'import_key_for_this_address': 'The import key for this wallet address',
    'tip_import_key_for_this_address': 'Please keep your import key in a safe place. Do not share it with anyone.',
};