window.language = window.language || {};
window.language['jp'] = {
    'total': '合計',
    'locked': 'ロック',
    'available': '支出可能',
    'send': '送信',
    'sending': '送信中...',
    'submit': 'OK',
    'center_password': 'パスワード',
    'profile': '個人情報',
    'center_logout': 'ログアウト',
    'change_btn': '変更',
    'wallet_password': 'ウォレットのパスワード',

    'menu_home': 'トップページ',
    'menu_send': '送金',
    'menu_transactions': 'トランザクション',

    'yourwallet': 'ウォレットのアドレス',
    'transactions': 'トランザクション',
    'recent_transactions': '最近のトランザクション',
    'block': 'ブロック',
    'date': '日付',
    'hash': 'トランザクションハッシュ',
    'amount': '金額',
    'pending': '未決',

    'pay_to': '宛先アドレス',
    'amount': '金額',
    'fee': '手数料',
    'anonymity_level': '匿名のレベル',
    'payment_id': 'Payment ID <small>(オプショナル)</small>',

    'unknown_error': '原因不明のエラー',
    'tip_amount': '金額を入力してください',
    'tip_fee': '手数料を入力してください',
    'tip_copy_clipboard': 'クリップボードにコピーする',
    'tip_copied': 'ウォレットのアドレスをコピーされた',
    'tip_wallet_password': 'ウォレットのパスワードを入力してください',
    'tip_send_success': '送金は成功しました',
    'tip_change_password': '新しいパスワードを入力してください',
    'tip_email_password': 'メールアドレスとパスワードを入力してください',
    'tip_email_err': 'メールアドレスが間違っていた',
    'tip_enter_email': 'メールアドレスを入力してください',
    'tip_enter_password': 'パスワードを入力してください',
    'tip_you_signed': '会員登録完了しました、ログインしてください',
    'tip_agree': '<a href="/tos.html" target="_blank">会員規約</a>に同意する',
    'tip_length_6': 'パスワードは必ず6文字以上でお願いします。',
    'tip_passwords_confirm': '入力したパスワードが一致していません',
    'tip_must_agree': '会員規約をお読みになり、すべての内容に同意のうえ、次へ進んでください。',

    'reg_title': 'BBSちゃん 会員登録',
    'login_title': 'ログイン',
    'email_address': 'メールアドレス',
    'signing': 'ログイン中...',
    'registering': '登録中...',
    'sign_in': 'ログイン',
    'here_sign': 'ログイン',
    'here_reg': '会員登録',
    'not_account': 'アカウントがない?',
    'has_account': 'アカウントがありました?',
    'password': 'パスワード',
    'confirm_password': 'パスワードの確認',
    'register': '会員登録',
    'tip_repeat_wallet_password': 'ウォレットのパスワードを再入力してください',
    'tip_mixing': '無効な匿名のレベル',
    'tip_backup_copied': 'バックアップ情報がコピーされた',
    'tip_wallet_password_warning': 'ウォレットのパスワードを入力してください。6文字以上で構成されている必要があります。<br>BBSちゃんは暗号化されたウォレットを保存するだけ。<br>次の画面で秘密認証キーを見ることになります<br>パスワードと秘密認証キーを忘れてしまった場合、ウォレットのパスワード再設定ができない。<br>',
    'tip_backup_warning': '<b>下記のウォレット秘密認証キーを確かにバックアップしてください。</b><br><br><b>紛失しない</b> 紛失した場合、再発行することができません。<br><b>共有しない</b> 不正利用を防ぐために、インターネットにアップロードしないください。<br><b>バックアップしてください</b> 黄金と同じように、大切に保管してください。<br>',
    'tip_backup_info': '以下の情報をバックアップしてください',
    'new_wallet_title': '新しいウォレットを作成',
    'backup_keys_title': '認証キーのバックアップ',
    'backup_understand': 'ウォレットのアドレスと秘密認証キーをバックアップしました',
    'confirmed': '検証済み',
    'cancelled': 'キャンセルされた',
    'no_transaction': 'トランザクションがない',
    'transaction_details': 'トランザクションの詳細',
    'tx_details_hash': 'ハッシュ',
    'tx_details_status': 'ステータス',
    'tx_details_block_number': 'ブロック',
    'tx_details_time': '日付',
    'tx_details_confirmations': '検証済み',
    'tx_details_unlock_time': 'アンロックタイム',
    'tx_details_amount': '金額',
    'tx_details_transaction_fee': '手数料',
    'tx_details_payment_id': 'Payment ID',
    'destination_address': '宛先アドレス',
    'unlock_wallet': 'ウォレットのアンロック',
    'unlock_processing': 'ただいまデータを同期中<br>しばらくお待ち下さい',
    'server_status': 'サーバーのステータス',
    'last_synced': '最終同期ブロック',
    'last_updated': '最終同期日時',
    'maintenance': 'メンテナンス',
    'walletAddress': 'ウォレットのアドレス',
    'viewSecret': 'View Secret バックアップ情報',
    'spendSecret': 'Spend Secret バックアップ情報',
    'newWalletPassword': '新しいパスワード',
    'tip_wallet_password_changed_success': 'ウォレットのパスワードが正常に変更されました',
    'tip_view_phase': '新しいウォレットを作成する時、24単語のView Secretバックアップ情報',
    'tip_spend_phase': '新しいウォレットを作成する時、24単語のSpend Secretバックアップ情報',
    'reset_wallet_password': 'ウォレットのパスワードをリセット',
    'create_new_address': '新しいアドレスを作成',
    'login_html_title': 'ログイン | BBSちゃん',
    'register_html_title': '会員登録 | BBSちゃん',
    'reset_html_title': 'パスワードをリセット | BBSちゃん',
    'modify_account_password': 'アカウントのパスワードの変更',
    'old_password': '古いパスワード',
    'new_password': '新しいパスワード',
    'confirm_new_password': '新しいパスワードの確認',
    'tip_account_password_changed_success': 'アカウントのパスワードが正常に変更されました',
    'tip_old_new_password': '古いパスワードと新しいパスワードを入力してください',
    'tip_email': 'メールアドレスを入力してください',
    'reset_account_password': 'アカウントのパスワードのリセット',
    'send_reset_mail': 'パスワードをリセットするためのメールを送信する',
    'forget_password': 'パスワードを忘れてしまった?',
    'reset_password': 'パスワードをリセットする',
    'verify_account': 'アカウントの認証',
    'verify_account_html_title': 'アカウントの認証 | BBSちゃん',
    'verification_code': '認証コード',
    'tip_incorrect_verification_code': '無効な認証コードです',
    'tip_verification': '空白な認証コードです',
    'verifying': '認証中...',
    'tip_account_verified': '会員認証完了しました、ログインしてください',
    'tip_needs_verification': 'BBSちゃんへようこそ！ご登録いただきありがとうございます。 <br>確認メールのステップに従い登録を完了させます。 <br>認証コードの有効期限は２４時間以内です、ご注意ください。',
    'tip_reset_email_sent': ' ご協力いただきありがとうございます！確認メールのステップに従いリセットを完了させます',
    'tip_new_password_email_sent': ' ご協力いただきありがとうございます！新しいパスワードをあなたのメールボックスに送信しました。',
    'tip_wrong_verification_for_new_password': '無効な認証コードまたはメールアドレス',
    'tos_html_title': '会員規約 | BBSちゃん',
    'tip_pay_to': '宛先アドレスを入力してください',
    'invalid_amount': '無効な金額',
    'amount_too_big': '金額が大き過ぎ',
    'tip_new_address': 'あなたは最大2個ウォレットのアドレスがを保有することができます。',
    'api_access': 'API 権限',
    'generate_app_key': 'App Keyを作成する',
    'revoke_app_key': 'App Keyを取り消す',
    'tip_api_access': 'App Id と App Key は、あなたのサビースに統合することがでます',
    'tip_existing_api_access': '以下のApp Idを作成されました. <br>安全の為にの、App Keyは非表示です。 <br>App Keyを紛失した場合、App Keyを再作成してください. ',
    'tip_new_api_access': 'App Keyを安全な場所に保管してください。今後はApp Keyは非表示です。',
    'app_id': 'App Id',
    'tip_app_id': 'App Id はウォレットの標識',
    'app_key': 'App Key',
    'tip_app_key': 'App Keyを安全な場所に保管してください',
    'generate_import_key': 'Import Keyを作成',
    'recover_from_backup': 'バックアップから回復?',
    'tip_generate_import_key': 'Import keyを生成し、デスクトップのウォレットに導入できます。<br>File > Import key に導入してください',
    'import_key_for_this_address': 'ウォレットのImport key',
    'tip_import_key_for_this_address': 'Import keyを安全な場所に保管してください。誰でも共有しないください。',
    'inactive_address': '休眠ウォレット',
    'inactive_address_tip': 'このウォレットは３０日利用がされていないのため、無効にしました。 <br> このウォレットをダウンロードして、デスクトップのウォレットでご利用してください: <a href="https://bbscoin.xyz/download/">https://bbscoin.xyz/download/</a><br>ウォレットのアンロックを入力して、Import Keyを作成する。<br>そして File > Import key に導入してください.'
};