window.language = window.language || {};
window.language['kor'] = {
    'total': '총 개수',
    'locked': '보류중',
    'available': '전송 가능',
    'send': '전송',
    'sending': '전송중...',
    'submit': '보내기',
    'center_password': '암호',
    'profile': '프로필',
    'center_logout': '로그아웃',
    'change_btn': '변경',
    'wallet_password': '지갑 암호',

    'menu_home': '기본',
    'menu_send': '전송',
    'menu_transactions': '전송 내역',

    'yourwallet': '내 지갑 주소',
    'transactions': '전송 내역',
    'recent_transactions': '최근 내역',
    'block': '블록',
    'date': '날짜',
    'hash': '해쉬',
    'amount': '수량',
    'pending': '처리중',

    'pay_to': '수신 지갑 주소',
    'amount': '수량',
    'fee': '수수료',
    'anonymity_level': '익명성 레벨',
    'payment_id': '주소 Payment ID  <small>(선택가능)</small>',

    'unknown_error': '미확인 에러',
    'tip_amount': '수량을 입력 하세요',
    'tip_fee': '수수료를 입력 하세요',
    'tip_copy_clipboard': '클립보드로 복사 완료',
    'tip_copied': '지갑 주소 복사를 완료 했습니다',
    'tip_wallet_password': '지갑 암호를 입력 하세요',
    'tip_send_success': '전송 신청을 완료 했습니다. 전송 해쉬: <br>',
    'tip_change_password': '암호를 변경 하세요',
    'tip_email_password': '이메일과 암호를 입력 하세요',
    'tip_email_err': '이메일 형식 검증 오류가 발생 했습니다',
    'tip_enter_email': '이메일 주소',
    'tip_enter_password': '암호',
    'tip_you_signed': '등록을 완료 했습니다. 로그인을 하세요.',
    'tip_agree': '서비스 및 이용 약관에 동의<a href="/tos.html" target="_blank">해주세요</a>',
    'tip_length_6': ' 암호는 최소한 6자 이상이여야 합니다',
    'tip_passwords_confirm': '암호가 다릅니다',
    'tip_must_agree': '서비스 및 이용 약관에 동의 해주세요',

    'reg_title': 'BBS.money 계정 등록',
    'login_title': 'BBS.money에 오신걸 환영합니다',
    'email_address': '이메일 주소',
    'signing': '로그인 중...',
    'registering': '등록 중...',
    'sign_in': '로그인',
    'here_sign': ' 로그인',
    'here_reg': '여기서 등록',
    'not_account': '계정이 없으신가요?',
    'has_account': '이미 계정이 있으신가요?',
    'password': '암호',
    'confirm_password': '암호 재확인',
    'register': '등록',
    'tip_repeat_wallet_password': '지갑 암호를 다시 입력하세요',
    'tip_mixing': '익명성 레벨 오류',
    'tip_backup_copied': '백업 정보가 복사 되었습니다',
    'tip_wallet_password_warning': '신규 지갑에 새로운 암호를 설정 해주세요. 암호는 최소한 6자 이상이여야 합니다.<br>BBS.money는 암호화된 키를 서버에 저장합니다. <br>사용자의 개인 키가 다음 화면에 표시됩니다.<br>개인 키 분실시 지갑 복구가 불가능하니 참고 바랍니다.',
    'tip_backup_warning': '<b>다음은 사용자 지갑의 비밀 키 입니다. 반드시 백업을 해두세요.</b><br><br><b>잃어 버리지 마세요!</b> 분실 시 복구가 불가능 합니다.<br><b>공유도 하지 마세요.</b> 키가 악성피싱 사이트에 노출될 시 모든 자금이 도난 당할 수 있습니다.<br><b>백업은 필수 입니다.</b>안전한 곳에 보관하시길 바랍니다.<br>',
    'tip_backup_info': '다음과의 정보를 반드시 백업해 두세요',
    'new_wallet_title': '신규 지갑 생성',
    'backup_keys_title': '백업 키',
    'backup_understand': '지갑 주소와 비밀 키를 백업 했습니다',
    'confirmed': '확인 완료',
    'cancelled': '취소 완료',
    'no_transaction': '전송 내역 없음',
    'transaction_details': '전송 세부 내역',
    'tx_details_hash': '해쉬',
    'tx_details_status': '상태',
    'tx_details_block_number': '블록 번호',
    'tx_details_time': '시간',
    'tx_details_confirmations': '확인 수',
    'tx_details_unlock_time': '잠금 해제 시간',
    'tx_details_amount': 'Amount',
    'tx_details_transaction_fee': '전송 수수료',
    'tx_details_payment_id': '지갑 Payment ID',
    'destination_address': '수신자 지갑 주소',
    'unlock_wallet': '지갑 잠금 해제',
    'unlock_processing': '전송 중<br>잠시만 기다려 주세요',
    'server_status': '서버 상태',
    'last_synced': '마지막 동기화',
    'last_updated': '마지막 업데이트',
    'maintenance': '설정',
    'walletAddress': '지갑 주소',
    'viewSecret': '열람 비밀 키 백업 단어',
    'spendSecret': '전송 비밀 키 백업 단어',
    'newWalletPassword': '신규 지갑 암호',
    'tip_wallet_password_changed_success': '지갑 암호가 변경 되었습니다',
    'tip_view_phase': '지갑을 만들었을때 생성된 열람 비밀 키의 24개 단어',
    'tip_spend_phase': '지갑을 만들었을때 생성된 전송 비밀 키의 24개 단어',
    'reset_wallet_password': '지갑 암호 재설정',
    'create_new_address': '신규 지갑 생성',
    'login_html_title': '로그인 | BBS.money',
    'register_html_title': '등록 | BBS.money',
    'reset_html_title': '암호 재설정 | BBS.money',
    'modify_account_password': '계정 암호 변경',
    'old_password': '이전 암호',
    'new_password': '신규 암호',
    'confirm_new_password': '신규 암호 확인',
    'tip_account_password_changed_success': '계정 암호가 변경 되었습니다',
    'tip_old_new_password': '이전 암호와 신규 암호를 입력해 주세요',
    'tip_email': '이메일 주소를 입력해 주세요',
    'reset_account_password': '계정 암호 재설정',
    'send_reset_mail': '재설정 메일 보내기',
    'forget_password': '암호를 잃어 버리셨나요?',
    'reset_password': '암호 재설정',
    'verify_account': '계정 검증',
    'verify_account_html_title': '계정 검증 | BBS.money',
    'verification_code': '검증 코드',
    'tip_incorrect_verification_code': '미확인 검증 코드',
    'tip_verification': '검증 코드를 반드시 입력해 주세요',
    'verifying': '확인중...',
    'tip_account_verified': '계정이 검증 되었습니다. 로그인을 해주세요.',
    'tip_needs_verification': 'BBS.money에 등록을 감사합니다. <br>등록 완료를 위해 이메일에 있는 검증 절차를 확인해 주세요.<br>참고로 검증 코드는 24시간내에만 유효합니다.',
    'tip_reset_email_sent': '감사합니다. 암호 재설정에 관한 내용이 이메일로 전송 되었습니다.',
    'tip_new_password_email_sent': '감사합니다. 임시 암호가 이메일로 전송 되었습니다.',
    'tip_wrong_verification_for_new_password': '계정 확인 불가 또는 미확인 검증 코드',
    'tos_html_title': '서비스 및 이용 약관 | BBS.money',
    'tip_pay_to': '수신자 지갑 주소를 입력해 주세요',
    'invalid_amount': '미확인 수량',
    'amount_too_big': '수량 초과',
    'tip_new_address': '계정마다 최대 2개의 지갑을 생성할 수 있습니다.',
    'api_access': 'API 설정',
    'generate_app_key': '신규 앱 키 생성',
    'revoke_app_key': '앱 키 파기',
    'tip_api_access': '앱 ID와 앱 키를 이용하여 BBS.money를 제3자 서비스와 연동할 수 있습니다.',
    'tip_existing_api_access': '다음과 같은 앱 ID가 생성 되었습니다.<br>보안을 위해 앱 키는 보이지 않습니다. <br>앱 키를 분실시 새로운 키를 생성 하시길 바랍니다.',
    'tip_new_api_access': '앱 키를 반드시 안전한 곳에 보관 하세요. 마지막으로 표시가 됩니다.',
    'app_id': '앱 ID',
    'tip_app_id': '앱 ID는 지갑 주소 확인을 위해 사용합니다',
    'app_key': '앱 키',
    'tip_app_key': '앱 키를 안전한 곳에 보관 하세요. 매우 중요한 비밀 정보 입니다.',
    'generate_import_key': '개인 키 생성',
    'recover_from_backup': '백업 복원을 원하세요?',
    'tip_generate_import_key': '개인 키를 사용하여 BBS.money에서 데스크탑 개인 지갑으로 자금을 이동할 수 있습니다.<br>개인 키 정보를 데스크탑 지갑 파일(File) > 개인 키(Import key)로 복사해서 입력하시면 됩니다.',
    'import_key_for_this_address': '이 지갑의 개인 키',
    'tip_import_key_for_this_address': '개인 키를 안전한 곳에 보관 하세요. 아무와도 공유를 하지 마세요.',
};
