window.language = window.language || {};
window.language['pt_BR'] = {
    'total': 'Total',
    'locked': 'Bloqueado',
    'available': 'Disponível',
    'send': 'ENVIAR',
    'sending': 'ENVIANDO...',
    'submit': 'Envar',
    'center_password': 'senha',
    'profile': 'Perfil',
    'center_logout': 'Sair',
    'change_btn': 'alterar',
    'wallet_password': 'Senha da Carteira',

    'menu_home': 'Visão Geral',
    'menu_send': 'Enviar',
    'menu_transactions': 'Transações',

    'yourwallet': 'Sua Carteira',
    'transactions': 'Transações',
    'recent_transactions': 'Transações Recentes',
    'block': 'Bloco',
    'date': 'Data',
    'hash': 'Hash',
    'amount': 'Valor',
    'pending': 'Pendente',

    'pay_to': 'Endereço de Destino',
    'amount': 'Valor',
    'fee': 'Fee',
    'anonymity_level': 'Nível de Anonimato',
    'payment_id': 'ID de Pagamento <small>(opcional)</small>',

    'unknown_error': 'Erro Desconhecido',
    'tip_amount': 'Por favor, informe o valor',
    'tip_fee': 'Por favor, insira a taxa fee',
    'tip_copy_clipboard': 'Clique para Copiar',
    'tip_copied': 'Endereço Copiado com Sucesso',
    'tip_wallet_password': 'Informe a senha da Carteira',
    'tip_send_success': 'Transação foi submetida, hash de transcação é: <br>',
    'tip_change_password': 'Alterar Senha',
    'tip_email_password': 'Por favor, insira seu e-mail e senha',
    'tip_email_err': 'Erro de validação do e-mail',
    'tip_enter_email': 'Email',
    'tip_enter_password': 'Senha',
    'tip_you_signed': 'Você se registrou com sucesso, faça o login.',
    'tip_agree': 'Eu aceito os <a href="/tos.html" target="_blank">Termos de Uso e Serviço</a>',
    'tip_length_6': 'A senha deve ser maior de 6 Caracteres',
    'tip_passwords_confirm': 'As senhas não combinam',
    'tip_must_agree': 'Você deve concordar com os Termos de Uso e Serviço',

    'reg_title': 'Crie uma Conta no BBS.money',
    'login_title': 'Bem vindo ao BBS.money',
    'email_address': 'Email',
    'signing': 'Entrando...',
    'registering': 'Registrando...',
    'sign_in': 'Entrar',
    'here_sign': ' Entrar',
    'here_reg': ' Cadastre-se Aqui',
    'not_account': 'Não tem uma conta?',
    'has_account': 'Você já tem uma conta?',
    'password': 'Senha',
    'confirm_password': 'Confirme a Senha',
    'register': 'Cadastrar',
    'tip_repeat_wallet_password': 'Confirme a senha da Carteira',
    'tip_mixing': 'Nível de anonimato errado',
    'tip_backup_copied': 'Informações de Backup foram copiadas',
    'tip_wallet_password_warning': 'Por favor, escolha uma senha para sua nova carteira. Deve ser maior que 6 caracteres.<br>BBS.money armazena apenas chaves criptografadas no servidor. <br>Suas chaves privadas serão mostradas na próxima tela.<br>Por favor, note que não podemos recuperar sua carteira se você perder.',
    'tip_backup_warning': '<b>As chaves seguintes são suas chaves secretas para esta carteira. Por favor, certifique-se de salvá-los.</b><br><br><b>Não perca isso!</b> Não pode ser recuperado se você o perder.<br><b>Não compartilhe!</b> Seus fundos serão roubados se você usar esse arquivo em um site malicioso / de phishing.<br><b> Faça um Backup!</b> Seguro como os milhões de dólares que um dia pode valer.<br>',
    'tip_backup_info': 'Por favor, faça o backup após as informações',
    'new_wallet_title': 'Criar uma Nova Carteira',
    'backup_keys_title': 'Backup de Chaves',
    'backup_understand': 'Eu fiz o backup do meu endereço e chaves secretas',
    'confirmed': 'Confirmado',
    'cancelled': 'Cancelado',
    'no_transaction': 'Nenhum Registro de Transações',
    'transaction_details': 'Detalhes da Transação',
    'tx_details_hash': 'Hash',
    'tx_details_status': 'Status',
    'tx_details_block_number': 'Número de Blocos',
    'tx_details_time': 'Hora',
    'tx_details_confirmations': 'Confirmações',
    'tx_details_unlock_time': 'Tempo para Desbloqueio',
    'tx_details_amount': 'Valor',
    'tx_details_transaction_fee': 'Fee da Transação',
    'tx_details_payment_id': 'ID do Pagamento',
    'destination_address': 'Endereço de Destino',
    'unlock_wallet': 'Desbloquear Carteira',
    'unlock_processing': 'Processando Transações<br> Aguarde um Pouco',
    'server_status': 'Status do Servidor',
    'last_synced': 'Última Sincronização',
    'last_updated': 'Última Atualização',
    'maintenance': 'Manutenção',
    'walletAddress': 'Endereço da Carteira',
    'viewSecret': 'Ver frases de backup secretas',
    'spendSecret': 'Gastar Chaves Secretas de Backup',
    'newWalletPassword': 'Nova Senha da Carteira',
    'tip_wallet_password_changed_success': 'A senha da carteira foi alterada com sucesso',
    'tip_view_phase': 'A frase de 24 palavras para ver a chave secreta quando você criou a carteira',
    'tip_spend_phase': 'A frase de 24 palavras para gastar a chave secreta quando você criou a carteira',
    'reset_wallet_password': 'Resertar Senha da Carteira',
    'create_new_address': 'Criar um Novo Endereço',
    'login_html_title': 'Login | BBS.money',
    'register_html_title': 'Cadastre-se | BBS.money',
    'reset_html_title': 'Resetar Senha| BBS.money',
    'modify_account_password': 'Modificar senha da Conta',
    'old_password': 'Senha Antiga',
    'new_password': 'Nova Senha',
    'confirm_new_password': 'Confirmar Nova Senha',
    'tip_account_password_changed_success': 'Senha da Conta Alterada com Sucesso',
    'tip_old_new_password': 'Por favor informe sua antiga e nova senha',
    'tip_email': 'Por favor informe seu email',
    'reset_account_password': 'Resetar Senha da Conta',
    'send_reset_mail': 'Enviar email de Reset',
    'forget_password': 'Esqueceu sua senha?',
    'reset_password': 'Resetar Senha',
    'verify_account': 'Verificar Conta',
    'verify_account_html_title': 'Verificar Conta | BBS.money',
    'verification_code': 'Código de Verificação',
    'tip_incorrect_verification_code': 'Código de Verificação Incorreto',
    'tip_verification': 'O Código de Verificação não pode ser vazio',
    'verifying': 'Verificando...',
    'tip_account_verified': 'Conta Verificada com Sucesso. Faça Login',
    'tip_needs_verification': 'Obrigado por se registrar no BBS.money. <br>Para concluir seu registro, verifique seu e-mail para obter instruções de ativação da conta. <br>Por favor, observe que o código de verificação expira em 24 horas.',
    'tip_reset_email_sent': 'Obrigado, um e-mail com detalhes sobre como redefinir a senha foi enviado para a conta correspondente.',
    'tip_new_password_email_sent': 'Obrigado, um email com a nova senha temporária foi enviada.',
    'tip_wrong_verification_for_new_password': 'Não é possível encontrar a conta ou o código de verificação é inválido.',
    'tos_html_title': 'Termo de Uso e Serviço | BBS.money',
    'tip_pay_to': 'Por favor, informe o endereço do destinatário',
    'invalid_amount': 'Valor Inválido',
    'amount_too_big': 'Quantidade muito grande',
    'tip_new_address': 'Cada conta pode criar no máximo dois endereços de carteira no momento.',
    'api_access': 'Acesso a API',
    'generate_app_key': 'Gerar Nova Chave do APP',
    'revoke_app_key': 'Revogar Chave de App',
    'tip_api_access': 'App Id e App Key permite integrar BBS.money com terceiros e outros serviços.',
    'tip_existing_api_access': 'O ID do aplicativo a seguir foi gerado para esse endereço. <br>Para sua proteção, não mostramos a chave do aplicativo.<br>Se você perder a sua App Key, você deve gerar uma nova. ',
    'tip_new_api_access': 'Por favor, mantenha sua chave de aplicativo em um local seguro. Nós não vamos mostrar de novo.',
    'app_id': 'ID do App',
    'tip_app_id': 'ID do App é usado para identificar esse endereço de carteira',
    'app_key': 'Chave do App',
    'tip_app_key': 'A chave do App deve ser armazenada em um local seguro. Por favor, trate isso como sua carteira secreta.',
    'generate_import_key': 'Gerar e Importar a Chave',
    'recover_from_backup': 'Recuperar a partir de um Backup?',
    'tip_generate_import_key': 'Você pode gerar a chave de importação para importar sua carteira da Web para a carteira da área de trabalho.<br>Por favor clique "Arquivo" > "Importar Chave" na carteira da área de trabalho, cole a chave de importação.',
    'import_key_for_this_address': 'A chave de importação para este endereço de carteira',
    'tip_import_key_for_this_address': 'Por favor, mantenha sua chave de importação em um local seguro. Não compartilhe com ninguém.',
};
